// Date: 19.10.2012 11:17:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package de.take_weiland.CameraCraft.Client.Models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelDigitalCamera extends ModelBase {
  //fields
    ModelRenderer Body1;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer Button1;
    ModelRenderer Button2;
    ModelRenderer Flash_Bottom;
    ModelRenderer Flash_Top;
  
  public ModelDigitalCamera() {
	  textureWidth = 64;
	  textureHeight = 64;
    
      Body1 = new ModelRenderer(this, 0, 9);
      Body1.addBox(0F, 0F, 0F, 14, 1, 1);
      Body1.setRotationPoint(-7F, 23F, 0F);
      Body1.setTextureSize(64, 64);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
      Body2 = new ModelRenderer(this, 0, 11);
      Body2.addBox(0F, 0F, 0F, 16, 8, 1);
      Body2.setRotationPoint(-8F, 15F, 0F);
      Body2.setTextureSize(64, 64);
      Body2.mirror = true;
      setRotation(Body2, 0F, 0F, 0F);
      Body3 = new ModelRenderer(this, 0, 20);
      Body3.addBox(0F, 0F, 0F, 14, 1, 1);
      Body3.setRotationPoint(-7F, 14F, 0F);
      Body3.setTextureSize(64, 64);
      Body3.mirror = true;
      setRotation(Body3, 0F, 0F, 0F);
      Button1 = new ModelRenderer(this, 0, 22);
      Button1.addBox(0F, 0F, 0F, 2, 1, 1);
      Button1.setRotationPoint(-6F, 13F, 0F);
      Button1.setTextureSize(64, 64);
      Button1.mirror = true;
      setRotation(Button1, 0F, 0F, 0F);
      Button2 = new ModelRenderer(this, 6, 22);
      Button2.addBox(0F, 0F, 0F, 3, 2, 1);
      Button2.setRotationPoint(3F, 12F, 0F);
      Button2.setTextureSize(64, 64);
      Button2.mirror = true;
      setRotation(Button2, 0F, 0F, 0F);
      Flash_Bottom = new ModelRenderer(this, 14, 22);
      Flash_Bottom.addBox(0F, 0F, 0F, 4, 1, 1);
      Flash_Bottom.setRotationPoint(-2F, 13F, 0F);
      Flash_Bottom.setTextureSize(64, 64);
      Flash_Bottom.mirror = true;
      setRotation(Flash_Bottom, 0F, 0F, 0F);
      Flash_Top = new ModelRenderer(this, 24, 22);
      Flash_Top.addBox(0F, 0F, 0F, 2, 1, 1);
      Flash_Top.setRotationPoint(-1F, 12F, 0F);
      Flash_Top.setTextureSize(64, 64);
      Flash_Top.mirror = true;
      setRotation(Flash_Top, 0F, 0F, 0F);
  }
  
  public void renderCamera() {
    Body1.render(0.0625F);
    Body2.render(0.0625F);
    Body3.render(0.0625F);
    Button1.render(0.0625F);
    Button2.render(0.0625F);
    Flash_Bottom.render(0.0625F);
    Flash_Top.render(0.0625F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z) {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}