package de.take_weiland.CameraCraft.Common.Gui;

/**
 * List of the known Gui Types
 * @author diesieben07
 *
 */
public enum GuiScreens {
	/**
	 * the camera inventory
	 */
	CAMERA_INVENTORY,
	/**
	 * the photo processor inventory
	 */
	PHOTO_PROCESSOR,
	/**
	 * the photo station inventory
	 */
	PHOTO_STATION, // 
	/**
	 * view the photos of the camera / the photo being held in the hand
	 */
	VIEW_PHOTOS_CURRENT_ITEM,
	/**
	 *  view the photo of a photo placed on the wall
	 */
	VIEW_PHOTOS_ENTITY,
	/**
	 * view the photos of an ItemPhotoStorage stored in a tileEntity (e.g. a PhotoStation)
	 * Tile Entity must be an Instance of IPhotoSource
	 */
	VIEW_PHOTOS_TILE_ENTITY,
	
	/**
	 * show the camera inventory when the camera is inside a tileEntityCamera
	 */
	CAMERA_INVENTORY_TILE_ENTITY;
	
	/**
	 * creates the Id to be used in {@link net.minecraft.src.EntityPlayer#openGui EntityPlayer.openGui}
	 * @return the Id
	 */
	public int toGuiId() {
		return ordinal();
	}
	
	public boolean isViewPhotos() {
		return this == VIEW_PHOTOS_CURRENT_ITEM || this == VIEW_PHOTOS_ENTITY || this == VIEW_PHOTOS_TILE_ENTITY;
	}
	
	/**
	 * gets the GuiScreen type from an Id generated by {@link #toGuiId()}
	 * @param id the id
	 * @return the GuiScreen type represented by this id
	 */
	public static GuiScreens fromGuiId(int id) {
		return id < values().length ? values()[id] : null;
	}

}
